index:
    path: /
    controller: App\Controller\TodoController::index
form_handler:
    methods: POST
    path: /addtask
    controller: App\Controller\TodoController::formHandler
delete_task:
    path: /delete/{$id}
    controller: App\Controller\TodoController::deleteTask
    